insert into love_blog_tbl(subject, content, publish_time) values ('给Eval的信', '宝贝! 生日快乐', CURRENT_TIME)
insert into love_blog_tbl(subject, content, publish_time) values ('测试1', '测试1数据', CURRENT_TIME)
insert into love_blog_tbl(subject, content, publish_time) values ('测试2', '测试2数据', CURRENT_TIME)
insert into love_blog_tbl(subject, content, publish_time) values ('测试3', '测试3数据', CURRENT_TIME)
insert into love_blog_tbl(subject, content, publish_time) values ('测试4', '测试4数据', CURRENT_TIME)
insert into love_blog_tbl(subject, content, publish_time) values ('测试5', '测试5数据', CURRENT_TIME)